# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_mon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13scheduler_mon.proto\"F\n\x0cProtoMonInfo\x12\x14\n\x0cnetwork_name\x18\x01 \x01(\t\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x01\x12\x13\n\x0butilization\x18\x03 \x01(\x01\"Q\n\x12ProtoMonDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0butilization\x18\x02 \x01(\x01\x12\x13\n\x0b\x64\x65vice_arch\x18\x03 \x01(\t\"\x83\x02\n\x18ProtoMonStreamFramesInfo\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\x12\x32\n\x10stream_direction\x18\x02 \x01(\x0e\x32\x18.ProtoMonStreamDirection\x12\x1a\n\x12\x62uffer_frames_size\x18\x03 \x01(\x05\x12\x1c\n\x14pending_frames_count\x18\x04 \x01(\x05\x12 \n\x18min_pending_frames_count\x18\x05 \x01(\x05\x12 \n\x18max_pending_frames_count\x18\x06 \x01(\x05\x12 \n\x18\x61vg_pending_frames_count\x18\x07 \x01(\x01\"f\n\x15ProtoMonNetworkFrames\x12\x14\n\x0cnetwork_name\x18\x01 \x01(\t\x12\x37\n\x14streams_frames_infos\x18\x02 \x03(\x0b\x32\x19.ProtoMonStreamFramesInfo\"\x9b\x01\n\x08ProtoMon\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12%\n\x0enetworks_infos\x18\x02 \x03(\x0b\x32\r.ProtoMonInfo\x12\x30\n\x10net_frames_infos\x18\x03 \x03(\x0b\x32\x16.ProtoMonNetworkFrames\x12)\n\x0c\x64\x65vice_infos\x18\x04 \x03(\x0b\x32\x13.ProtoMonDeviceInfo*s\n\x17ProtoMonStreamDirection\x12+\n\'PROTO__STREAM_DIRECTION__HOST_TO_DEVICE\x10\x00\x12+\n\'PROTO__STREAM_DIRECTION__DEVICE_TO_HOST\x10\x01\x42\x02H\x03\x62\x06proto3')

_PROTOMONSTREAMDIRECTION = DESCRIPTOR.enum_types_by_name['ProtoMonStreamDirection']
ProtoMonStreamDirection = enum_type_wrapper.EnumTypeWrapper(_PROTOMONSTREAMDIRECTION)
PROTO__STREAM_DIRECTION__HOST_TO_DEVICE = 0
PROTO__STREAM_DIRECTION__DEVICE_TO_HOST = 1


_PROTOMONINFO = DESCRIPTOR.message_types_by_name['ProtoMonInfo']
_PROTOMONDEVICEINFO = DESCRIPTOR.message_types_by_name['ProtoMonDeviceInfo']
_PROTOMONSTREAMFRAMESINFO = DESCRIPTOR.message_types_by_name['ProtoMonStreamFramesInfo']
_PROTOMONNETWORKFRAMES = DESCRIPTOR.message_types_by_name['ProtoMonNetworkFrames']
_PROTOMON = DESCRIPTOR.message_types_by_name['ProtoMon']
ProtoMonInfo = _reflection.GeneratedProtocolMessageType('ProtoMonInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMONINFO,
  '__module__' : 'scheduler_mon_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMonInfo)
  })
_sym_db.RegisterMessage(ProtoMonInfo)

ProtoMonDeviceInfo = _reflection.GeneratedProtocolMessageType('ProtoMonDeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMONDEVICEINFO,
  '__module__' : 'scheduler_mon_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMonDeviceInfo)
  })
_sym_db.RegisterMessage(ProtoMonDeviceInfo)

ProtoMonStreamFramesInfo = _reflection.GeneratedProtocolMessageType('ProtoMonStreamFramesInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMONSTREAMFRAMESINFO,
  '__module__' : 'scheduler_mon_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMonStreamFramesInfo)
  })
_sym_db.RegisterMessage(ProtoMonStreamFramesInfo)

ProtoMonNetworkFrames = _reflection.GeneratedProtocolMessageType('ProtoMonNetworkFrames', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMONNETWORKFRAMES,
  '__module__' : 'scheduler_mon_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMonNetworkFrames)
  })
_sym_db.RegisterMessage(ProtoMonNetworkFrames)

ProtoMon = _reflection.GeneratedProtocolMessageType('ProtoMon', (_message.Message,), {
  'DESCRIPTOR' : _PROTOMON,
  '__module__' : 'scheduler_mon_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMon)
  })
_sym_db.RegisterMessage(ProtoMon)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PROTOMONSTREAMDIRECTION._serialized_start=702
  _PROTOMONSTREAMDIRECTION._serialized_end=817
  _PROTOMONINFO._serialized_start=23
  _PROTOMONINFO._serialized_end=93
  _PROTOMONDEVICEINFO._serialized_start=95
  _PROTOMONDEVICEINFO._serialized_end=176
  _PROTOMONSTREAMFRAMESINFO._serialized_start=179
  _PROTOMONSTREAMFRAMESINFO._serialized_end=438
  _PROTOMONNETWORKFRAMES._serialized_start=440
  _PROTOMONNETWORKFRAMES._serialized_end=542
  _PROTOMON._serialized_start=545
  _PROTOMON._serialized_end=700
# @@protoc_insertion_point(module_scope)
